import type { JobFormData } from "@/features/jobs/components/job-form";

export interface JobTemplate {
  id: string;
  title: string;
  description: string;
  tags: string[];
  data: Partial<JobFormData>;
}

export const JOB_TEMPLATES: JobTemplate[] = [
  {
    id: "junior_frontend",
    title: "Junior Frontend Engineer",
    description:
      "Entry-level role for developers early in their career. Work on real features with mentorship from senior engineers.",
    tags: ["Engineering", "Frontend", "Entry-level"],
    data: {
      title: "Junior Frontend Engineer",
      description:
        "We're looking for a Junior Frontend Engineer to join our product team. You'll work on real customer-facing features with close mentorship from senior engineers. This is a great opportunity to grow your skills in a supportive environment while shipping code that users see every day.",
      requirements: [
        "1+ years of experience with React or similar framework",
        "Solid understanding of HTML, CSS, and JavaScript",
        "Basic knowledge of Git and version control workflows",
        "Willingness to learn and ask questions",
        "Some portfolio or personal projects to share",
      ],
      screeningQuestions: [
        "Are you authorized to work in the UK without visa sponsorship?",
        "This role is hybrid in London. Are you able to commute to the office, or relocate if needed?",
        "What are your salary expectations for this role?",
      ],
      experienceLevel: "junior",
      workplaceType: "hybrid",
      employmentType: "full_time",
      location: "London, UK",
      salaryMin: 35000,
      salaryMax: 55000,
      salaryCurrency: "GBP",
      teamSize: 4,
      headcount: 1,
    },
  },
  {
    id: "senior_backend",
    title: "Senior Backend Engineer",
    description:
      "Design and build core infrastructure. Own services end-to-end and mentor junior engineers.",
    tags: ["Engineering", "Backend", "Senior"],
    data: {
      title: "Senior Backend Engineer",
      description:
        "We're hiring a Senior Backend Engineer to own critical services and infrastructure decisions. You'll design APIs, optimize data models, and mentor junior team members. This role requires deep technical expertise and the ability to balance velocity with long-term maintainability.",
      requirements: [
        "5+ years of backend development experience",
        "Deep expertise in at least one of: Node.js, Python, Go, or Rust",
        "Strong database design and optimization skills",
        "Experience building and maintaining production APIs at scale",
        "Comfortable with distributed systems and async architectures",
        "Track record of mentoring junior engineers",
      ],
      screeningQuestions: [
        "This role is fully remote but requires overlap with US timezones. Can you commit to those working hours?",
        "Are you authorized to work in your country of residence for a full-time role?",
        "What are your salary expectations for this role?",
        "What is your current notice period or earliest available start date?",
      ],
      experienceLevel: "senior",
      workplaceType: "remote",
      employmentType: "full_time",
      location: "Remote (US timezone overlap)",
      salaryMin: 180000,
      salaryMax: 250000,
      salaryCurrency: "USD",
      teamSize: 6,
      headcount: 2,
    },
  },
  {
    id: "react_frontend",
    title: "React Frontend Engineer",
    description:
      "Build polished UI components and design systems. Focus on performance and accessibility.",
    tags: ["Engineering", "Frontend", "React"],
    data: {
      title: "React Frontend Engineer",
      description:
        "Join our frontend team to build and maintain our design system and core product UI. You'll work closely with designers to ship accessible, performant components that power the entire application.",
      requirements: [
        "3+ years of professional React experience",
        "Strong TypeScript skills",
        "Experience with component libraries or design systems",
        "Understanding of web performance optimization",
        "Knowledge of accessibility standards (WCAG)",
      ],
      screeningQuestions: [
        "Are you authorized to work in Germany without visa sponsorship?",
        "This role is remote within the EU. Are you based in or able to work from an EU timezone?",
        "What are your salary expectations (in EUR) for this role?",
      ],
      experienceLevel: "mid",
      workplaceType: "remote",
      employmentType: "full_time",
      location: "Berlin, Germany",
      salaryMin: 65000,
      salaryMax: 95000,
      salaryCurrency: "EUR",
      teamSize: 5,
      headcount: 1,
    },
  },
  {
    id: "product_manager",
    title: "Product Manager",
    description:
      "Own product roadmap and execution. Work cross-functionally with design, engineering, and leadership.",
    tags: ["Product"],
    data: {
      title: "Product Manager",
      description:
        "We're looking for a Product Manager to own a key product area from discovery to delivery. You'll work with designers, engineers, and customers to identify opportunities, define requirements, and ship features that move metrics.",
      requirements: [
        "3+ years of product management experience in a software company",
        "Track record of shipping features that improved key metrics",
        "Strong analytical skills — comfortable with data and A/B tests",
        "Excellent written and verbal communication",
        "Experience working with engineering teams in agile environments",
      ],
      screeningQuestions: [
        "Are you authorized to work in the US without visa sponsorship?",
        "This role is hybrid in New York. Are you able to commute to the office, or relocate if needed?",
        "What are your salary expectations for this role?",
      ],
      experienceLevel: "mid",
      workplaceType: "hybrid",
      employmentType: "full_time",
      location: "New York, NY",
      salaryMin: 140000,
      salaryMax: 190000,
      salaryCurrency: "USD",
      teamSize: 3,
      headcount: 1,
    },
  },
  {
    id: "ux_designer",
    title: "UX Designer",
    description:
      "Design intuitive user experiences. Conduct research, create prototypes, and work closely with engineers.",
    tags: ["Design", "UX"],
    data: {
      title: "UX Designer",
      description:
        "We're seeking a UX Designer to improve how users interact with our product. You'll conduct user research, create wireframes and prototypes, and collaborate with engineers to ensure designs are implemented faithfully.",
      requirements: [
        "3+ years of UX design experience for digital products",
        "Proficiency in Figma and prototyping tools",
        "Experience conducting user interviews and usability tests",
        "Strong portfolio showing end-to-end design process",
        "Comfortable working in agile teams with engineers",
      ],
      screeningQuestions: [
        "Are you authorized to work in the Netherlands without visa sponsorship?",
        "This role is onsite in Amsterdam. Are you currently based there, or willing to relocate?",
        "What are your salary expectations (in EUR) for this role?",
      ],
      experienceLevel: "mid",
      workplaceType: "onsite",
      employmentType: "full_time",
      location: "Amsterdam, Netherlands",
      salaryMin: 55000,
      salaryMax: 80000,
      salaryCurrency: "EUR",
      teamSize: 2,
      headcount: 1,
    },
  },
  {
    id: "devops_engineer",
    title: "DevOps / Platform Engineer",
    description:
      "Build and maintain CI/CD, infrastructure, and developer tooling. Focus on reliability and automation.",
    tags: ["Engineering", "Infrastructure"],
    data: {
      title: "DevOps / Platform Engineer",
      description:
        "Join our platform team to build the infrastructure and tooling that keeps our engineering team productive. You'll own CI/CD pipelines, cloud infrastructure, and observability systems.",
      requirements: [
        "4+ years of DevOps or platform engineering experience",
        "Strong experience with AWS, GCP, or Azure",
        "Proficiency with Terraform or similar IaC tools",
        "Experience with Kubernetes and containerization",
        "Strong scripting skills (Python, Bash, or Go)",
        "Familiarity with monitoring and alerting (Datadog, Grafana, etc.)",
      ],
      screeningQuestions: [
        "This role is remote within EU timezones. Are you based in or able to work from an EU timezone?",
        "Are you authorized to work in your country of residence for a full-time role?",
        "What are your salary expectations for this role?",
        "What is your current notice period or earliest available start date?",
      ],
      experienceLevel: "senior",
      workplaceType: "remote",
      employmentType: "full_time",
      location: "Remote (EU timezone)",
      salaryMin: 90000,
      salaryMax: 140000,
      salaryCurrency: "EUR",
      teamSize: 3,
      headcount: 1,
    },
  },
  {
    id: "data_engineer",
    title: "Data Engineer",
    description:
      "Build data pipelines and infrastructure. Support analytics and ML teams with reliable data systems.",
    tags: ["Engineering", "Data"],
    data: {
      title: "Data Engineer",
      description:
        "We're looking for a Data Engineer to build and maintain our data infrastructure. You'll design pipelines, ensure data quality, and support our analytics and ML initiatives with reliable, well-modeled data.",
      requirements: [
        "3+ years of data engineering experience",
        "Strong SQL and Python skills",
        "Experience with data warehouses (Snowflake, BigQuery, or Redshift)",
        "Familiarity with orchestration tools (Airflow, dbt, or similar)",
        "Understanding of data modeling and schema design",
        "Experience with streaming data (Kafka, Pub/Sub) is a plus",
      ],
      screeningQuestions: [
        "Are you authorized to work in Canada without visa sponsorship?",
        "This role is hybrid in Toronto. Are you able to commute to the office, or relocate if needed?",
        "What are your salary expectations for this role?",
      ],
      experienceLevel: "mid",
      workplaceType: "hybrid",
      employmentType: "full_time",
      location: "Toronto, Canada",
      salaryMin: 110000,
      salaryMax: 160000,
      salaryCurrency: "CAD",
      teamSize: 4,
      headcount: 1,
    },
  },
  {
    id: "mobile_engineer",
    title: "Mobile Engineer (iOS)",
    description:
      "Build native iOS features. Work on performance, animations, and seamless user experiences.",
    tags: ["Engineering", "Mobile", "iOS"],
    data: {
      title: "Mobile Engineer (iOS)",
      description:
        "Join our mobile team to build and improve our iOS app. You'll work on features that users interact with daily, focusing on performance, smooth animations, and a polished native experience.",
      requirements: [
        "3+ years of iOS development experience",
        "Strong Swift and UIKit/SwiftUI skills",
        "Experience with Core Data or other persistence layers",
        "Understanding of iOS app architecture patterns (MVVM, Coordinator, etc.)",
        "Experience with app store submission and review processes",
        "Familiarity with unit and UI testing on iOS",
      ],
      screeningQuestions: [
        "Are you authorized to work in the US without visa sponsorship?",
        "This role is hybrid in San Francisco. Are you able to commute to the office, or relocate if needed?",
        "What are your salary expectations for this role?",
      ],
      experienceLevel: "mid",
      workplaceType: "hybrid",
      employmentType: "full_time",
      location: "San Francisco, CA",
      salaryMin: 150000,
      salaryMax: 210000,
      salaryCurrency: "USD",
      teamSize: 3,
      headcount: 1,
    },
  },
  {
    id: "security_engineer",
    title: "Security Engineer",
    description: "Protect our systems and data. Build security tooling and lead incident response.",
    tags: ["Engineering", "Security"],
    data: {
      title: "Security Engineer",
      description:
        "We're hiring a Security Engineer to protect our platform and customer data. You'll identify vulnerabilities, build security automation, and lead incident response when issues arise.",
      requirements: [
        "4+ years of experience in application or infrastructure security",
        "Strong understanding of web application security (OWASP Top 10)",
        "Experience with cloud security (AWS IAM, VPC, etc.)",
        "Proficiency in at least one programming language",
        "Experience with security tooling (SAST, DAST, SCA)",
        "Familiarity with compliance frameworks (SOC 2, GDPR) is a plus",
      ],
      screeningQuestions: [
        "Are you authorized to work in the US without visa sponsorship?",
        "This role is fully remote within the US. Are you currently based in the US?",
        "What are your salary expectations for this role?",
        "What is your current notice period or earliest available start date?",
      ],
      experienceLevel: "senior",
      workplaceType: "remote",
      employmentType: "full_time",
      location: "Remote (US)",
      salaryMin: 170000,
      salaryMax: 240000,
      salaryCurrency: "USD",
      teamSize: 2,
      headcount: 1,
    },
  },
  {
    id: "qa_engineer",
    title: "QA Engineer",
    description:
      "Ensure product quality through automated testing, test strategy, and release processes.",
    tags: ["Engineering", "QA"],
    data: {
      title: "QA Engineer",
      description:
        "We're looking for a QA Engineer to own our testing strategy and automated test suite. You'll work with engineers to catch bugs early, improve test coverage, and ensure confident releases.",
      requirements: [
        "3+ years of QA or test engineering experience",
        "Experience with automated testing frameworks (Playwright, Cypress, Selenium)",
        "Strong understanding of CI/CD and test automation in pipelines",
        "Ability to write clear bug reports and reproduction steps",
        "Experience with API testing and performance testing is a plus",
        "Familiarity with JavaScript/TypeScript or Python for test scripts",
      ],
      screeningQuestions: [
        "This role is remote within the EU. Are you based in or able to work from an EU timezone?",
        "Are you authorized to work in your country of residence for a full-time role?",
        "What are your salary expectations for this role?",
      ],
      experienceLevel: "mid",
      workplaceType: "remote",
      employmentType: "full_time",
      location: "Remote (EU)",
      salaryMin: 60000,
      salaryMax: 95000,
      salaryCurrency: "EUR",
      teamSize: 4,
      headcount: 1,
    },
  },
  {
    id: "content_writer",
    title: "Content Writer",
    description: "Create clear, engaging content for our blog, docs, and marketing materials.",
    tags: ["Marketing", "Content"],
    data: {
      title: "Content Writer",
      description:
        "We're seeking a Content Writer to create technical and marketing content that resonates with developers and decision-makers. You'll write blog posts, documentation, case studies, and email campaigns.",
      requirements: [
        "2+ years of content writing experience, preferably in B2B SaaS",
        "Ability to write clearly about technical topics for mixed audiences",
        "Strong editing and proofreading skills",
        "Experience with SEO basics and content strategy",
        "Comfortable interviewing subject matter experts",
        "Portfolio of published writing samples",
      ],
      screeningQuestions: [
        "This role is fully remote. Which country and timezone are you based in?",
        "Are you authorized to work in your country of residence for a full-time role?",
        "What are your salary expectations for this role?",
      ],
      experienceLevel: "mid",
      workplaceType: "remote",
      employmentType: "contract",
      location: "Remote",
      salaryMin: 350,
      salaryMax: 600,
      salaryCurrency: "USD",
      teamSize: 2,
      headcount: 1,
    },
  },
  {
    id: "sales_dev_rep",
    title: "Sales Development Representative",
    description:
      "Generate pipeline through outbound outreach. Work closely with Account Executives.",
    tags: ["Sales"],
    data: {
      title: "Sales Development Representative",
      description:
        "Join our sales team as an SDR to identify and qualify new business opportunities. You'll research prospects, craft personalized outreach, and set meetings for our Account Executives.",
      requirements: [
        "1-2 years of sales or customer-facing experience",
        "Strong written and verbal communication skills",
        "Comfortable with cold outreach and rejection",
        "Experience with CRM tools (HubSpot, Salesforce)",
        "Self-motivated and target-driven",
        "Interest in technology and SaaS products",
      ],
      screeningQuestions: [
        "Are you authorized to work in the US without visa sponsorship?",
        "This role is onsite in Austin. Are you currently based there, or willing to relocate?",
        "What are your salary expectations for this role?",
      ],
      experienceLevel: "junior",
      workplaceType: "onsite",
      employmentType: "full_time",
      location: "Austin, TX",
      salaryMin: 55000,
      salaryMax: 75000,
      salaryCurrency: "USD",
      teamSize: 6,
      headcount: 2,
    },
  },
];
